
depth = ..

NAME = needle
MODULE_LIBS= ../visualize ../defolib ../meshlib
MODULE_INCLUDES=../visualize ../defolib ../meshlib
MODULE_CXXFLAGS =
MODULE_DEFINES=-DOPENGL
EXTRA_LDFLAGS=-lgsl -lgslcblas -lm 
EXTRA_DIST_FILES =  

HELP2MAN_EXECS = lilypond
STEPMAKE_TEMPLATES= c++ executable 
LD=$(CXX)
include $(depth)/make/stepmake.make 
